### ISSUE TITLE
This is WCAG public repo no longer available

### ISSUE THREAD

**Issue by waako** [CivicActions/accessibility-data-reference#1]
https://github.com/canaxess/thisiswcag returns a 404 now.

But did find what must be a [fork of original repo](https://github.com/rjabdurrahman/thisiswcag-beta) so can still get to a [data json file](https://github.com/rjabdurrahman/thisiswcag-beta/blob/main/data/json.js)

**Comment by mgifford** [comment]
Good point. I couldn't get a better forked or cached version.

I did reach out to the folks at:
https://github.com/canaxess/

But I will take the data json file remove that reference to the GitHub Repo

**Comment by mgifford** [comment]
I've updated the link to point to the json file.
